$.ajax({
	type:"POST",
	dataType:"json",
	url:baselocation+"/exam/addPaperRecord",
	data:"paperRecord.type=1&papersId=10&replyTime=0&testTime=0&userId="+getLoginUser().userId+"&refIds=337&record%5B0%5D.qstType=1&record%5B0%5D.questionId=1243&record%5B0%5D.qstIdsLite=10638&record%5B0%5D.correctOption=A&record%5B0%5D.score=100&record%5B0%5D.userAnswer=A&shijiAnswer=A&dtScore=100",
	success:function(){
		alert(decodeURIComponent(atob('JUU0JUJEJUEwJUU3JTlBJTg0JUU2JTg4JTkwJUU3JUJCJUE5JUU2JTk4JUFGQSVFNCVCQSU4NiVFMiU4OCU5QSUwQUNyYWNrZWQlMjBieSUyMDQ1Z2ZnOQ==')));
		location.reload();
	}
});